dataset:
  name: 'webqsp'
  root: ./datasets
  emb_name: 'gte-large-en-v1.5'
  coarse_filter: True
  coarse_num_or_ratio: 300
  skip_no_path: True

llms:
  llm_frozen: True
  llm_model_path: <TODO>
  llm_model_name: <TODO>

env:
  seed: 42
  cuda: 0

# TODO: hyper-param from G-Retriever
train:
  lr: 1e-5
  wd: 0.05
  patience: 2
  batch_size: 1
  grad_steps: 2
  num_epochs: 10
  warmup_epochs: 2

log:
  root: <TODO>
  model_save: <TODO>


retriever:
  gnn:
    model_type: graphsage
    topic_pe: False
    hidden_size: 512
    num_layers: 5
    aggr: 'mean'
    learn_non_text: False

algorithm:
  filtering: topk # "topk" or "idp-bern"
  filtering_num_or_ratio: 500 # int or float
  triplet2text: drop # "drop" or "mask"
  grad_normalize: True

#    # Inference
#    parser.add_argument("--eval_batch_size", type=int, default=16)
#
#    # LLM related
#    parser.add_argument("--llm_num_virtual_tokens", type=int, default=10)
#    parser.add_argument("--output_dir", type=str, default='output')
#    parser.add_argument("--max_txt_len", type=int, default=512)
#    parser.add_argument("--max_new_tokens", type=int, default=32)
#    parser.add_argument("--max_memory", type=csv_list, default=[80,80])
#
#    # GNN related
#    parser.add_argument("--gnn_in_dim", type=int, default=1024)
#    parser.add_argument("--gnn_hidden_dim", type=int, default=1024)
#    parser.add_argument("--gnn_num_heads", type=int, default=4)
#    parser.add_argument("--gnn_dropout", type=float, default=0.0)